### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by ole-tange** [pauldotknopf/twitter-dump#12]
I try running `build.sh`. It fails:

~~~
$ bash build.sh 
/home/tange/tmp/twitter-dump/build/scripts/Build.csproj(3,3): error MSB4019: The imported project "/home/tange/tmp/twitter-dump/build/scripts/Buildary/Build.proj" was not found. Confirm that the expression in the Import declaration "Buildary/Build.proj" is correct, and that the file exists on disk.

The build failed. Fix the build errors and run again.
~~~

Did you forget to add `build/scripts/Buildary/Build.proj` to git?

**Comment by pauldotknopf** [comment]
```git submodule update --init```

**Comment by ole-tange** [comment]
~~~
$ git submodule update --init
Submodule 'build/scripts/Buildary' (https://github.com/pauldotknopf/dotnet-buildary.git) registered for path 'build/scripts/Buildary'
Cloning into '/home/vagrant/twitter-dump/build/scripts/Buildary'...
Submodule path 'build/scripts/Buildary': checked out 'c3dd8634dc88e1243ec29e0ca8cfa6e2623a0350'
~~~
Looks good.

But:
~~~
$ bash -x build.sh 
+++ dirname build.sh
++ cd .
++ pwd
+ SCRIPT_DIR=/home/vagrant/twitter-dump
+ cd /home/vagrant/twitter-dump
+ dotnet run -p ./build/scripts/Build.csproj --
Configuration: Release
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-gitversion does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
Unhandled exception. SimpleExec.NonZeroExitCodeException: The command exited with code 1.
   at SimpleExec.ProcessExtensions.Throw(Process process)
   at SimpleExec.Command.Read(String name, String args, String workingDirectory, Boolean noEcho, String windowsName, String windowsArgs, String echoPrefix, Action`1 configureEnvironment)
   at Build.Buildary.Shell.ReadShell(String shell) in /home/vagrant/twitter-dump/build/scripts/Buildary/Shell.cs:line 42
   at Build.Buildary.GitVersion.GetGitVersion(String directory) in /home/vagrant/twitter-dump/build/scripts/Buildary/GitVersion.cs:line 15
   at Build.Program.Main(String[] args) in /home/vagrant/twitter-dump/build/scripts/Program.cs:line 19
~~~

**Comment by ole-tange** [comment]
After:

~~~
dotnet tool install --global GitVersion.Tool
~~~
I get:
~~~
$ bash -x build.sh 
+++ dirname build.sh
++ cd .
++ pwd
+ SCRIPT_DIR=/home/vagrant/twitter-dump
+ cd /home/vagrant/twitter-dump
+ dotnet run -p ./build/scripts/Build.csproj --
Configuration: Release
Version: 0.2.0-alpha.10
Build: Starting... (default)
Build: build: Starting...
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: /home/vagrant/twitter-dump/AptTool.sln
Build: build: SimpleExec.NonZeroExitCodeException: The command exited with code 1.
   at SimpleExec.ProcessExtensions.Throw(Process process)
   at SimpleExec.Command.Run(String name, String args, String workingDirectory, Boolean noEcho, String windowsName, String windowsArgs, String echoPrefix, Action`1 configureEnvironment)
   at Build.Buildary.Shell.RunShell(String shell) in /home/vagrant/twitter-dump/build/scripts/Buildary/Shell.cs:line 25
   at Build.Program.<>c__DisplayClass0_0.<Main>b__2() in /home/vagrant/twitter-dump/build/scripts/Program.cs:line 51
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Bullseye.Internal.ActionTarget.RunAsync(Boolean dryRun, Boolean parallel, Logger log, Func`2 messageOnly)
Build: build: Failed! The command exited with code 1. (526 ms)
Build: ───────────────────────────────
Build: Duration        Outcome  Target
Build: ──────────────  ───────  ──────
Build: 526 ms  100.0%  Failed!  build 
Build: ───────────────────────────────
Build: Failed! (default) (539 ms)
~~~
